package stringutil

const LOWERCASE_LETTERS = "abcdefghijklmnopqrstuvwxyz"
const LOWERCASE_LETTERS_LEN = len(LOWERCASE_LETTERS)

const UPPERCASE_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
const UPPERCASE_LETTERS_LEN = len(UPPERCASE_LETTERS)

const LETTERS = LOWERCASE_LETTERS + UPPERCASE_LETTERS
const LETTERS_LEN = len(LETTERS)

const NUMBERS = "0123456789"
const NUMBERS_LEN = len(NUMBERS)
