package stringutil

const LOWERCASE_LETTERS string = "abcdefghijklmnopqrstuvwxyz"
const LOWERCASE_LETTERS_LEN int = len(LOWERCASE_LETTERS)

const UPPERCASE_LETTERS string = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
const UPPERCASE_LETTERS_LEN int = len(UPPERCASE_LETTERS)

const LETTERS string = LOWERCASE_LETTERS + UPPERCASE_LETTERS
const LETTERS_LEN int = len(LETTERS)

const NUMBERS string = "0123456789"
const NUMBERS_LEN int = len(NUMBERS)
